coverage:
  status:
    project:
      default:
        informational: true

    patch:
      default:
        informational: true

ignore:
  - test/**
  - build/**
  - android/**
  - doc/**
  - ios/**
  - android/**
